services:
  api:
    build:
      context: .
      args:
        NODE_ENV: development 
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/inventory?schema=public
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma migrate deploy &&
             node -r tsconfig-paths/register dist/infrastructure/http/server.js"
    depends_on:
      db:
        condition: service_healthy
      wms:
        condition: service_started

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  wms:
    image: node:20-alpine
    working_dir: /wms
    volumes:
      - ./wms-mock:/wms
    command: sh -c "npm i -g http-server && http-server -p 4000 -c-1 ."
    ports:
      - "4000:4000"

volumes:
  pgdata:
